[project]
name = "ntfyer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pendulum>=3.1.0",
    "sqlalchemy>=2.0.43",
]
